name: key_runner
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flame: 1.20.0
  flame_forge2d: 0.18.2+1
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_ce: 2.5.0+2
  hive_ce_flutter: 2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
